#
#
#

SOURCES = prikazipiksele.c
INCLUDEDIRS = /usr/include/opencv
LIBS = -lopencv_highgui -lopencv_core -lopencv_imgproc
OUTPUT = prikazipiksele

#
#
#

compile:
	$(CC) $(SOURCES) -I$(INCLUDEDIRS) $(LIBS) -o $(OUTPUT)